import type { Metadata } from "next";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import NavBar from "./(nav)/page";
import { shadesOfPurple } from "@clerk/themes";
import { jaJP } from "@clerk/localizations";

export const metadata: Metadata = {
  title: "Nexample",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const local = {
    signIn: {
      start: {
        subtitle: "pineapple pizza",
      },
    },
  };
  return (
    <ClerkProvider appearance={{ theme: shadesOfPurple }} localization={local}>
      <html lang="en">
        <body
          className={`antialiased bg-light-peach font-mont text-light-text`}
        >
          <NavBar />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
